name: cortadoeg
description: "Cortado Coffee Egypt Business System."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  #general dependencies
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.0
  flutter_onboarding_slider: ^1.0.11
  animated_notch_bottom_bar: ^1.0.3
  logger: ^2.4.0
  smooth_sheets: ^0.10.2
  sweetsheet: ^0.4.0
  #flutter_tts: ^4.0.2
  connectivity_plus: ^6.1.0
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  async: ^2.11.0
  url_launcher: ^6.3.1
  font_awesome_flutter: ^9.0.0
  loading_animation_widget: ^1.3.0
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  line_icons: ^2.0.3
  auto_size_text: ^3.0.0
  image_picker: ^1.1.2
  cross_file_image: ^1.1.0
  rolling_switch: ^0.0.2
  animated_snack_bar: ^0.4.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  share_plus: ^10.1.1
  permission_handler: ^11.3.1
  sidebarx: ^0.17.1
  pinput: ^5.0.0
  two_dimensional_scrollables: ^0.3.3
  lottie: ^3.1.3
  flutter_local_notifications: ^18.0.1
  google_sign_in: ^6.2.1
  animated_custom_dropdown: 3.1.1
  sign_button: ^2.0.6
  #flutter_facebook_auth: ^7.1.1
  badges: ^3.1.2
  flutter_svg: ^2.0.13
  hawk_fab_menu: ^1.2.0
  anim_search_app_bar: ^1.0.3
  input_quantity: ^2.5.0
  expansion_tile_group: ^2.1.0
  flutter_slidable: ^3.1.2
  intl_phone_field: ^3.2.0
  draggable_bottom_sheet: ^1.0.2
  bottom_sheet: ^4.0.4
  pull_to_refresh: ^2.0.0
  passcode_screen: ^2.0.1
  bcrypt: ^1.1.3
  calendar_date_picker2: ^1.1.7
  dropdown_button2: ^2.3.9
  flutter_esc_pos_network: ^1.0.3
  image: ^4.0.0
  http: ^1.2.2
  roundcheckbox: ^2.0.5
  device_preview: ^1.2.0
  ping_discover_network_forked: ^0.0.1
  data_table_2: ^2.5.18


  #state management dependencies
  get: ^4.6.6

  #data base dependencies
  firebase_analytics: ^11.3.3
  firebase_app_check: ^0.3.1+4
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.2.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  firebase_crashlytics: ^4.1.3
  firebase_performance: ^0.10.0+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  branding: assets/images/branding_light.png
  color_dark: "#121212"
  image_dark: assets/images/logo_white.png
  branding_dark: assets/images/branding_dark.png

  android_12:
    image: assets/images/android12splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/android12splash_dark.png
    icon_background_color_dark: "#121212"

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/gifs/
    - assets/lottie_animations/
    - assets/svg/

