// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxnKfnqtPcN0OfOgqdHV1QUL5TTZG_9uE',
    appId: '1:571315776995:web:767f051e46bb54806584d6',
    messagingSenderId: '571315776995',
    projectId: 'cortadoegypt',
    authDomain: 'cortadoegypt.firebaseapp.com',
    storageBucket: 'cortadoegypt.firebasestorage.app',
    measurementId: 'G-RY6L2H44HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0al34m7eJRkNJxCvE0wJ7axqfqKD5aRU',
    appId: '1:571315776995:android:2f1d92da147aa0896584d6',
    messagingSenderId: '571315776995',
    projectId: 'cortadoegypt',
    storageBucket: 'cortadoegypt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn2Ls2RoILsQpjDUj16Zpv3E7uz4oUBgo',
    appId: '1:571315776995:ios:1562cd97789eb5126584d6',
    messagingSenderId: '571315776995',
    projectId: 'cortadoegypt',
    storageBucket: 'cortadoegypt.firebasestorage.app',
    iosBundleId: 'com.example.cortadoeg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn2Ls2RoILsQpjDUj16Zpv3E7uz4oUBgo',
    appId: '1:571315776995:ios:1562cd97789eb5126584d6',
    messagingSenderId: '571315776995',
    projectId: 'cortadoegypt',
    storageBucket: 'cortadoegypt.firebasestorage.app',
    iosBundleId: 'com.example.cortadoeg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxnKfnqtPcN0OfOgqdHV1QUL5TTZG_9uE',
    appId: '1:571315776995:web:0baefe8ebeb51c116584d6',
    messagingSenderId: '571315776995',
    projectId: 'cortadoegypt',
    authDomain: 'cortadoegypt.firebaseapp.com',
    storageBucket: 'cortadoegypt.firebasestorage.app',
    measurementId: 'G-NYZG43D6D1',
  );
}
